# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KingCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('cal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number_of_firsts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number_of_seconds', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number_of_desserts', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('today_eat', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(blank=True, choices=[(b'banquet', b'banquet'), (b'diet', b'diet'), (b'thirsty', b'thirsty'), (b'big_ones', b'big_ones'), (b'little_ones', b'little_ones'), (b'not_me', b'not_me')], max_length=45, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('cal', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('order', models.CharField(blank=True, choices=[(b'first', b'first'), (b'second', b'second'), (b'dessert', b'dessert'), (b'drink', b'drink')], max_length=45, null=True)),
                ('flavour', models.CharField(blank=True, choices=[(b'sweet', b'sweet'), (b'spicy', b'spicy'), (b'salty', b'salty'), (b'tasty', b'tasty')], max_length=45, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
