# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-12 15:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('active_player', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ListGameDiscardCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.PlayerCard')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='ListGameKingCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.KingCard')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='ListGamePlayerCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.PlayerCard')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Game')),
            ],
        ),
        migrations.CreateModel(
            name='ListPlayerCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.PlayerCard')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('weight', models.PositiveSmallIntegerField()),
                ('saving_not_me_cards', models.PositiveSmallIntegerField()),
                ('saving_active_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.PlayerCard')),
                ('saving_card_pile', models.ManyToManyField(related_name='card_pile', through='game.ListPlayerCard', to='card.PlayerCard')),
            ],
        ),
        migrations.AddField(
            model_name='listplayercard',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='saving_discard_pile',
            field=models.ManyToManyField(related_name='discard_pile', through='game.ListGameDiscardCard', to='card.PlayerCard'),
        ),
        migrations.AddField(
            model_name='game',
            name='saving_king_cards',
            field=models.ManyToManyField(related_name='king_cards', through='game.ListGameKingCard', to='card.KingCard'),
        ),
        migrations.AddField(
            model_name='game',
            name='saving_player_cards',
            field=models.ManyToManyField(related_name='player_cards', through='game.ListGamePlayerCard', to='card.PlayerCard'),
        ),
        migrations.AddField(
            model_name='game',
            name='saving_players',
            field=models.ManyToManyField(related_name='players', to='game.Player'),
        ),
    ]
