# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-30 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('not_me_cards', models.PositiveSmallIntegerField()),
                ('active_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='card.PlayerCard')),
                ('card_pile', models.ManyToManyField(related_name='card_pile', to='card.PlayerCard')),
            ],
        ),
    ]
