# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 16:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='active_card',
        ),
        migrations.RemoveField(
            model_name='player',
            name='card_pile',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='not_me_cards',
        ),
    ]
